FROM python:3.14-slim

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN mkdir -p /app/api
WORKDIR /app/api


# Copy the application into the container.
COPY . /app
# COPY ./pyproject.toml ./uv.lock ./.python-version /app/api



RUN uv sync --frozen --no-cache
# RUN --mount=type=cache,target=/root/.cache/uv \
#     --mount=type=bind,source=uv.lock,target=uv.lock \
#     --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
#     uv sync --frozen --no-install-project --no-dev



# Run and attach with: 
# CMD ["tail", "-f", "/dev/null"]

# Run the application.
CMD ["/app/api/.venv/bin/fastapi", "run", "main.py", "--host", "0.0.0.0"]

# If running behind a proxy like Nginx or Traefik add --proxy-headers
# CMD ["/app/.venv/bin/fastapi", "run", "main.py", "--port", "80", "--host", "--proxy-headers"]